### ISSUE TITLE
Create New Script to Fetch AoC Competition Data

### ISSUE THREAD

**Issue by mike-weiner** [Minnesota-Computer-Club/MCC-Website-v2#152]
Let's create a new script called `pullAocLeaderboards2024.py` that is based on: https://github.com/Minnesota-Computer-Club/MCC-Website-v2/blob/04a2a847f292434c99205e3f1d7600e5992c3485/jobs/pullAocLeaderboards.py

We want the JSON that this script writes out to a file to be formatted like this: 

```
{
  "lastUpdatedAt": 1733021922,
  "schools": [
    {
      "city": "Rochester, MN",
      "efficiency": 1.5,
      "name": "Mayo High School",
      "stars": 3,
      "participants": 2
    },
    {
      "city": "Rochester, MN",
      "efficiency": 1.5,
      "name": "Century High School",
      "stars": 3,
      "participants": 2
    },
    ...
  ]
}
```

We will get a private AoC leaderboard code from various schools. This script will need to keep a dictionary of those private leaderboard codes and the school that owns it. 

It will then need to look through that list of AoC leaderboards, calculate the total number of stars earned in that leaderboard, how many participants are in that leaderboard, etc. and write that out to a file. 

We should be able to reuse quite a bit of the logic that exists in the current script today. 

Let me know if you run into any problems or need any help!

**Comment by NifleySnifley** [comment]
Should be done. Added `pullAocLeaderboards2024.py` script that produces `generatedData/schoolScoresXXXX.json` with information specified in the `.env` file and a `competition.json` file that specifies school names and leaderboard codes.
